name: CI

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SECRET }}
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: |
          git fetch
          npx commitlint --from=HEAD~1 --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from=${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to=${{ github.event.pull_request.head.sha }} --verbose
  
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SECRET }}
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies and buld app
        run: |
          npm ci --force
          npx playwright install --with-deps chromium
          npm run build

      - name: Run e2e tests
        run: |
          npm run e2e

      - name: Run unit tests
        run: |
          npm run test-ci

      - name: Run linter
        run: |
          npm run lint
          
          
      
      
